### PR TITLE
Bump compileSdkVersion to 31

### PR DESCRIPTION
**Pull request by carriehall**

### CODE REVIEW

**Review by JinneeJ — COMMENTED** [review]
Thanks for the change! Why do we need to update it without target sdk version? :)

**Comment by carriehall** [comment]
Thanks for the review @JinneeJ! It's a good question - I needed to bump the compile version as `androidx.lifecycle` required it for version 2.4.0, so I just bumped every module to `compileVersion` 31 for consistency. I didn't want to bump the target SDK in the same PR in case it introduced a regression, so that we could revert the PR without having the dependency bumps reverted too.

**Review by JinneeJ — APPROVED** [review]
Thanks for explaining! Though having different compile and target versions introduces "inconsistency" (in some way) in independent library and doing it only because of specific needs of internal project might be not optimal :) But on the other hand it's temporary so let's go with that :)

**Comment by carriehall** [comment]
Thanks for the review! I'll do the target sdk bump first thing next week 👍

**Pull request merged**
